language: java
sudo: true
jdk:
  - openjdk11
branches:
  only:
    - main
before_install:
  - chmod +x mvnw
deploy:
  on:
    branch: main
  provider: heroku
  api_key:
    secure: $SECURE_KEY
  app: $APP