language: java
sudo: true
jdk:
  - openjdk11
branches:
  only:
    - main
before_install:
  - export TZ=America/Sao_Paulo
  - chmod +x mvnw
deploy:
  on:
    branch: main
  provider: heroku
  api_key: $API_KEY
  app: $APP