language: java
sudo: true
jdk:
  - openjdk11
branches:
  only:
    - main
before_install:
  - chmod +x mvnw
deploy:
  on:
    branch: main
  provider: heroku
  api_key:
    secure: eTy6FOukXn/yiDLnZjKIw7hIUOU/GWZdRuiBtzwDoIMuYHo7ZyeNhVcIlPh3EXtBO2tzkkWFQCQzDR+EK2+ik/+I5lDlEaLoAQ/WQh41v5Dj5FmILnHiaTCezzKUSfhsVZEyaVbWxNv0dkM6z4owH7qN+JLx4yvOsSanKG4iO9r/bCynXzkw83M1EAtPJ/RO4EUOYC9rSHxTzZsz/gIPRTpGaFZD9SnZrSQ3a517dgIa2MwRS/Wd5vtPD8hAA2bRAIcjd0kf1HnDxaqqAmIz7LCVEw1kQeSNbxuiEInnXcKuaw+Xj2mCOhb8Rz6jheU5lYg7jdw4rPBTMlx5JyB4WQmfkJL+MvAGic4/asjM4F3Zud/HrCKuD8pbBySNxRJ2QODJMIK8m/4MNgBgB+yWAmJ/AnBd5Ej3rcRQlnhJnxcXBL26yAdZ5PTh6RlclWoUDW8NJaPq/jYAzIx63PpmQ/m2aAiYcvYxRxjy4hKJaVD94ApDUkoIRfCs4h21ocTHr3K91RswLP3fgcE8X5Sxzp3T+gFFuXyjUOJQMpTNo8qogpTHaxr1eSHwgFhsZPFN0eqvUGuOIknBeSoXzt17IL6XjFi5pp48zimcCSQQvhXB8ATG89u2ZYkr/nyoLT5iJdzjHvhqoxDYNvoJSm4jNq54C20N5B8GYJ+wAfL5FrY=
  app:
    secure: JZ3dYNX0vBR7ijxoDTbt/ftbLunPjcJFSJ3aNXWFxnujMdJPHjR54FnyvLDSC4bWKwDx84vjaZVUmy04rdMPuq8N2YEV3QjsWtqIYUT8koXz4g/BKJJ7TrwZjyCBuEMYm7G0jPk7pBMBvmWBMsokNK0c6MsipHpVQkOwNgbYgN8cJiu4O+LVkWdfDxFaD6efnk0Mysi7dcY5sGu9LCBmEM1gjB9xuB2bw9/IJcmVEJ23eDg/oL+2GKCR6EYpVr9b4iakZFfDuTFr4iTYy7txQRX6wr4niwV0ey6dBC1aN/9jVURLxSV0vj0ToCNNrbxrLD3JPHSZWTKkW9pOepB0RAVp/8BW3fVX1S2rCi9LW4ebcre6rMnUIF00UaCTh9jIFHxiU/bf+1wM7az8niDmMuUSDPZE35sMJTPTCwPDsaWDH/sYyM2p3QDWX4PDZyVIsmhqF/gVNZ+N4YUZXWSle5qk/e+D3Ui+V4JLe5JJ3LS2DRSPHw0jYtsC9HCgPkk/gvLR4yOmTcPZGXGjcrBTGQ8uMi+Nuj1GEbcextLs3OXSijcwqypqs4DJYGXtKtxx80zsmlBxaF1qmACfWqwpP5erdit2fWuStMzYB4OWL3gjqeB3XL35W86RMkHqN69Z1+XBFqSXrV+7yOZOo3h5dyAut8CN/e5uRbooaDxcGGg=
